//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEC_License.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CEC_License.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _1__管排標籤設定96 {
            get {
                object obj = ResourceManager.GetObject("_1__管排標籤設定96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _2__放置管排管段標籤96 {
            get {
                object obj = ResourceManager.GetObject("_2__放置管排管段標籤96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Image20220111111226 {
            get {
                object obj = ResourceManager.GetObject("Image20220111111226", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Image20220111111234 {
            get {
                object obj = ResourceManager.GetObject("Image20220111111234", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 副穿樑套管ICON合集_複製 {
            get {
                object obj = ResourceManager.GetObject("副穿樑套管ICON合集_複製", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 單管_多管V2__轉換__01__96dpi {
            get {
                object obj = ResourceManager.GetObject("單管&多管V2 [轉換]-01).96dpi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 單管_多管V2__轉換__02__96dpi {
            get {
                object obj = ResourceManager.GetObject("單管&多管V2 [轉換]-02).96dpi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 單管吊架設定_32pix {
            get {
                object obj = ResourceManager.GetObject("單管吊架設定-32pix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 圖塊轉換icon_32pix {
            get {
                object obj = ResourceManager.GetObject("圖塊轉換icon_32pix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 根據視圖範圍更新穿樑資訊_ {
            get {
                object obj = ResourceManager.GetObject("根據視圖範圍更新穿樑資訊_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_RC {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_RC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_RClink {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_RClink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_ST {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_ST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_STlink {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_STlink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_多管開口 {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_多管開口", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_多管開口link {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_多管開口link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_方形開口 {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_方形開口", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_方形開口link {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_方形開口link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_更新 {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_更新", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_編號 {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_編號", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_編號2 {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_編號2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_設定 {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_設定", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_逐層複製 {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_逐層複製", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_重編號 {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_重編號", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿樑套管ICON合集_重編號2 {
            get {
                object obj = ResourceManager.GetObject("穿樑套管ICON合集_重編號2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿牆套管ICON合集_多管方開口_svg {
            get {
                object obj = ResourceManager.GetObject("穿牆套管ICON合集_多管方開口_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿牆套管ICON合集_多管方開口link_svg {
            get {
                object obj = ResourceManager.GetObject("穿牆套管ICON合集_多管方開口link_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿牆套管ICON合集_局部更新_svg {
            get {
                object obj = ResourceManager.GetObject("穿牆套管ICON合集_局部更新_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿牆套管ICON合集_放置_svg {
            get {
                object obj = ResourceManager.GetObject("穿牆套管ICON合集_放置_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿牆套管ICON合集_放置link_svg {
            get {
                object obj = ResourceManager.GetObject("穿牆套管ICON合集_放置link_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿牆套管ICON合集_方開口_svg {
            get {
                object obj = ResourceManager.GetObject("穿牆套管ICON合集_方開口_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿牆套管ICON合集_方開口link_svg {
            get {
                object obj = ResourceManager.GetObject("穿牆套管ICON合集_方開口link_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿牆套管ICON合集_更新_svg {
            get {
                object obj = ResourceManager.GetObject("穿牆套管ICON合集_更新_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿牆套管ICON合集_編號_svg {
            get {
                object obj = ResourceManager.GetObject("穿牆套管ICON合集_編號_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿牆套管ICON合集_複製外參_svg {
            get {
                object obj = ResourceManager.GetObject("穿牆套管ICON合集_複製外參_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿牆套管ICON合集_複製逐層_svg {
            get {
                object obj = ResourceManager.GetObject("穿牆套管ICON合集_複製逐層_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 穿牆套管ICON合集_重新編號_svg {
            get {
                object obj = ResourceManager.GetObject("穿牆套管ICON合集_重新編號_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 預組ICON_清除標籤_svg_32 {
            get {
                object obj = ResourceManager.GetObject("預組ICON_清除標籤_svg_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 預組ICON_清除編號_svg_32 {
            get {
                object obj = ResourceManager.GetObject("預組ICON_清除編號_svg_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 預組ICON_產生ISO圖_svg_32 {
            get {
                object obj = ResourceManager.GetObject("預組ICON_產生ISO圖_svg_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 預組ICON_重新編號_svg_32 {
            get {
                object obj = ResourceManager.GetObject("預組ICON_重新編號_svg_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
